### ISSUE TITLE
Add ability to test standalone hive jobs 

### ISSUE THREAD

**Issue by jagatsingh** [CommBank/thermometer#23]
Example

Join table a table b insert to c

Test this job via maestro

Any hive query

**Comment by stephanh** [comment]
@kfish we already got support for testing hive queries as part of a load. The missing piece is a nice way to create and populate existing hive tables as part of the test set up.

If you use the Hive monad from ebenezer then your code needs to go into ebenezer to avoid circular dependencies.

**Comment by kfish** [comment]
Working on this in the hive-standalone branch on ebenezer

**Comment by kfish** [comment]
See https://github.com/CommBank/ebenezer/pull/100

**Comment by kfish** [comment]
This has been merged to ebenezer and util.etl
