### ISSUE TITLE
Reduce log output from hive and parquet

### ISSUE THREAD

**Issue by stephanh** [CommBank/thermometer#24]

**Comment by rowandavies** [comment]
We could do this via: https://github.com/Parquet/parquet-mr/issues/425

Also see: https://github.com/CommBank/coppersmith/blame/master/scalding/src/test/scala/commbank/coppersmith/scalding/ScaldingJobSpec.scala#L61 https://github.com/CommBank/coppersmith/commit/cfef3f8415626d60f3e388ec1d5b84c7340949a0

**Comment by jdcba** [comment]
Please re-test and close this issue if resolved with the latest version (thermometer 1.5.1-20170118093110-cf2dbd8 or higher: support for log reduction with Derby, Java Logging API and Parquet): https://commbank.github.io/thermometer/index.html
