### ISSUE TITLE
Old style thermometer tests brake with Scalding 0.13.1

### ISSUE THREAD

**Issue by stephanh** [CommBank/thermometer#39]
The old style thermometer tests no longer work when upgrading to Scalding 0.13.1.

Within the Maestro team we have stopped using them and now use the ExecutionSupport trait to run our tests which gives us a much cleaner and less hacky API.

@lancelet  @laurencer @SamRoberts what will be the impact on you if I remove the old API?

**Comment by SamRoberts** [comment]
@stephanh we have five tests which use the `TypedPipe` => `Verifiable` conversion and call `withFacts` on that.

What exactly breaks? Is it just the `Job` api, or the pipe api as well? Could we simply call `writeExecution` on these pipes and test with `ExecutionSupport` to fix it?

**Comment by stephanh** [comment]
au.com.cba.omnia.thermometer.example.TypedPsvSpec and au.com.cba.omnia.thermometer.example.IntegrationSpec fail. I have pushed the code as it to the branch scala211.

**Comment by SamRoberts** [comment]
Ok, I'll take a look tomorrow

**Comment by stephanh** [comment]
@lancelet @laurencer just want to make sure you are across this.

**Comment by stephanh** [comment]
@SamRoberts Unfortunately the way the old tests work is that they mutate a global flow and we then execute the flow. I don't really see a reasonable way in wrapping that with execution.

I will try and provide an API that allows you to test scalding pipes though.

**Comment by lancelet** [comment]
@stephanh thanks for the heads-up.

I think that @mjhopkins and I will have quite a bit of work to do to port our tests across; however, it's not insurmountable, and I would personally prefer to move forward. Do you have a specific link into the Maestro source tree of a test that formerly used the old approach and has now switched to the new one (as a template for us to look at initially)?

**Comment by stephanh** [comment]
@lancelet not at the top of my head for Maestro. However, I will convert the examples in Thermometer as part of the PR. I'm also happy to sit down and go through it. Unless I'm missing something the changes you need to make should be straightforward and you the thermometer API itself should be simpler as well.

**Comment by stephanh** [comment]
https://github.com/CommBank/thermometer/blob/master/core/src/test/scala/au/com/cba/omnia/thermometer/example/ExecutionSpec.scala is an Execution version of https://github.com/CommBank/thermometer/blob/master/core/src/test/scala/au/com/cba/omnia/thermometer/example/TypedPsvSpec.scala

**Comment by lancelet** [comment]
Thanks! :smile:

**Comment by SamRoberts** [comment]
@stephanh Ray has indicated he is happy to move to Execution

**Comment by stephanh** [comment]
@lancelet https://github.com/CommBank/thermometer/blob/scala211/core/src/test/scala/au/com/cba/omnia/thermometer/example/ScaldingSpec.scala also has a way to test a Scalding typed pipe or grouped directly.
