### ISSUE TITLE
Get Theremometer to clean up after the test

### ISSUE THREAD

**Issue by stephanh** [CommBank/thermometer#40]
Thermometer should delete the temp hdfs directory and hive db, etc. It should also be possible to prevent that easily for debugging.

**Comment by jdcba** [comment]
I’ve implemented a branch with optional support for deleting the thermometer-test* tmp directories (created by HadoopSupport) upon JVM shutdown. This can be enabled with environment variable `THERMOMETER_HADOOP_SUPPORT_OPTS=cleanup:shutdown`. A `reporting` option is also supported to print the sizes. The motivation for this is to prevent shared CI build agents from exhausting their /tmp space/inodes. Will raise a PR after writing tests.

**Comment by jdcba** [comment]
This is resolved in 1.5.9 as an opt-in feature. @toddmowen has suggested that it should be opt-out in a future version bump.
