### ISSUE TITLE
log4j.properties

### ISSUE THREAD

**Issue by jystic** [CommBank/thermometer#43]
Is it necessarily a good idea to have `log4j.properties` in a library?

I think I may be getting a situation where it's conflicting with my tests `log4j.properties` so I'm not getting the output that I want.

**Comment by stephanh** [comment]
It's a test library so this is only there to reduce the log spam produced when running tests. I don't think it is working anymore though. I think there is more log output now than there used to be before the upgrade.

**Comment by jystic** [comment]
Yes, but all of our test configurations that end up writing logs have their own `log4j.properties`, will the one in thermometer possibly conflict with that?

**Comment by stephanh** [comment]
If you have something in your resources folder it should take precedence.

Hadoop spams a lot of log output and thermometer should provide you with a nicer experience out of the box.

**Comment by jystic** [comment]
Ok, that's all I wanted to know about, as long as ours takes precedence.

**Comment by stephanh** [comment]
@jystic I'm pretty sure that with the upgrade the log4j.properties file in thermometer actually stopped being effective.

**Comment by jystic** [comment]
Yeah I think you're right. The reason I started investigating was because that `ThermometerHiveSpec` test I was running seems to be spitting out all kinds of junk.

**Comment by rowandavies** [comment]
See #44
