### ISSUE TITLE
Thermometer no longer seems to reduce test log spam downstream

### ISSUE THREAD

**Issue by stephanh** [CommBank/thermometer#44]
Downstream projects no longer seem to apply the log4j.properties provided by Thermometer and produce log output that should be suppressed.

**Comment by jdcba** [comment]
Please re-test and close this issue if resolved with the latest version (thermometer 1.5.1-20170118093110-cf2dbd8 or higher: support for log reduction with slf4j-simple): https://commbank.github.io/thermometer/index.html
