### ISSUE TITLE
Resource leak in HiveSupport

### ISSUE THREAD

**Issue by jdcba** [CommBank/thermometer#70]
There is a significant resource leak in [HiveSupport](https://github.com/CommBank/thermometer/blob/c0ea273a24607f15377718e41ef2e71205f55827/hive/src/main/scala/au/com/cba/omnia/thermometer/hive/HiveSupport.scala) because there’s no shutdown after each unit test is run. Thus, in any project with multiple unit tests, multiple metastore database daemons (Derby) are launched and continue to consume open file descriptors and threads for the entire test process until the JVM exits. This causes performance problems and ultimately our SBT builds fail with “Too many open files”.

**Comment by vineethvarghese** [comment]
Close it in some after test hook?

**Comment by jdcba** [comment]
Yes that is what I have been doing. Raised PR #71

**Comment by jdcba** [comment]
Resolved in v1.4.10
